apiVersion: apps/v1
kind: Deployment
metadata:
  name: unb-security
spec:
  replicas: 3
  strategy: 
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  selector:
    matchLabels:
      app: unb-security
  template:
    metadata:
      labels:
        app: unb-security
    spec:
      containers:
      - name: unb-security
        image: flpinheiro/unb.security
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
          protocol: TCP
        env:
          - name: ASPNETCORE_URLS
            value: http://+:80
